### ISSUE TITLE
no dimming option in HomeKit

### ISSUE THREAD

**Issue by luci84tm** [gutweiler/homebridge-platform-deconz#2]
Hi there, 
First of all I want to tank you for this plugin it is very useful :)
I do have an issue with it: I have 2 lights one while ikea tradfri and a tunablewhite  from OSRAM, and in home kit I see only a on/off switch, no other controls like dimming or white tune.
Any idea why ?

**Comment by gutweiler** [comment]
released new version 1.1.0, which includes #3
